### ISSUE TITLE
close please

### ISSUE THREAD

**Issue by E-enuts** [JustOptimize/return-ShowHiddenChannels#105]
Any of these issues aren't caused by this plugin im just saying

open settings = New discord update there is an fix in the betterdiscord offical server

Right click on any channel = I tested all my plugins and its caused by Permission viewer we just have to wait until the developer fixes it hopefully

(UPDATE ITS FIXED UPDATE UR DISCORD TO NEW VERSION)

**Comment by arianwen27** [comment]
So, right clicking should have been fixed in version 0.2.5 of the plugin. I also know "staff tag" causes issues with right clicking so make sure you try with all other plugins off

**Comment by DeathGod2k1** [comment]
No longer the case, all my plugins work correctly with the updated betterdiscord .asar but now it only crashes if i join a server with hidden channels, disabling it fixes the crashing

**Comment by arianwen27** [comment]
Update the plugin to 0.2.5 to fix the plugin related crash issues

**Comment by gmanc2** [comment]
I'm still getting crashes even with the asar patch. Also sometimes it states the meta was not found.

**Comment by xeroxayuki** [comment]
> I'm still getting crashes even with the asar patch. Also sometimes it states the meta was not found.

There is a way to use the showhiddenchannel plugin. You can use Discord PTB (its a beta test version of discord for future updates). 
Install better discord on discord PTB and you can use all plugins with no crashes. 
 
Also you can install normal discord and discord PTB together and login from the same device. 
So you can just use discord normally with your normal discord and open the discord PTB if you need to use the showhiddenchannel plugin.
